services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "80:80"         # Nginx
    environment:
      VITE_REACT_APP_BACKEND_URL: "http://localhost:8000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "8000:8000"     # FastAPI
    environment:
      SECRET: "my_secret_value"
      DATABASE_URL: "postgresql+asyncpg://postgres:password@db:5432/mydb"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: