"""add position to faqs

Revision ID: 0c93160348df
Revises: 87bae6980843
Create Date: 2025-05-13 21:17:33.191855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c93160348df'
down_revision: Union[str, None] = '87bae6980843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faqs', sa.Column('position', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faqs', 'position')
    # ### end Alembic commands ###
