"""add link and linktext to annoucments

Revision ID: 30a5984b07cd
Revises: 278f4ac83633
Create Date: 2025-03-20 22:30:38.518822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30a5984b07cd'
down_revision: Union[str, None] = '278f4ac83633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('link', sa.String(), nullable=True))
    op.add_column('announcements', sa.Column('linktext', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'linktext')
    op.drop_column('announcements', 'link')
    # ### end Alembic commands ###
