"""add link and linktext to FAQs

Revision ID: 30b062b26634
Revises: 30a5984b07cd
Create Date: 2025-03-20 22:48:29.914214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30b062b26634'
down_revision: Union[str, None] = '30a5984b07cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faqs', sa.Column('link', sa.String(), nullable=True))
    op.add_column('faqs', sa.Column('linktext', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faqs', 'linktext')
    op.drop_column('faqs', 'link')
    # ### end Alembic commands ###
