"""create api routes for schedule

Revision ID: 87bae6980843
Revises: 30b062b26634
Create Date: 2025-03-20 23:37:25.427810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87bae6980843'
down_revision: Union[str, None] = '30b062b26634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_schedules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('day', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('meeting_point', sa.String(), nullable=False),
    sa.Column('end_point', sa.String(), nullable=True),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('route_description', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('distance', sa.String(), nullable=False),
    sa.Column('leader', sa.String(), nullable=False),
    sa.Column('route_map_embed', sa.String(), nullable=True),
    sa.Column('start_point_embed', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_schedules_id'), 'route_schedules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_schedules_id'), table_name='route_schedules')
    op.drop_table('route_schedules')
    # ### end Alembic commands ###
