"""Add table for managing features

Revision ID: 94d2073fa271
Revises: 1bf7ee7f23a9
Create Date: 2025-01-30 02:41:23.143748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94d2073fa271'
down_revision: Union[str, None] = '1bf7ee7f23a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
